"Popup_ZombieSelect.res"
{
	"ZombieSelectPopupDlg"
	{
		"ControlName"		"CZombieSelectPopupDlg"
		"fieldName"		"ZombieSelectPopupDlg"
		"xpos"		"0"
		"ypos"		"200"
		"wide"		"181"
		"tall"		"416"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"settitlebarvisible"		"1"
		"title"		""
	}
	"Label1"
	{
		"ControlName"		"Label"
		"fieldName"		"Label1"
		"xpos"		"24"
		"ypos"		"26"
		"wide"		"133"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_ZombiSelectCount1"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"Label2"
	{
		"ControlName"		"Label"
		"fieldName"		"Label2"
		"xpos"		"24"
		"ypos"		"49"
		"wide"		"133"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_ZombiSelectCount2"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"zb1"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"zb1"
		"xpos"		"24"
		"ypos"		"79"
		"wide"		"64"
		"tall"		"54"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No1"
	{
		"ControlName"		"Label"
		"fieldName"		"No1"
		"xpos"		"27"
		"ypos"		"82"
		"wide"		"13"
		"tall"		"18"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"1"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"zb2"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"zb2"
		"xpos"		"93"
		"ypos"		"79"
		"wide"		"64"
		"tall"		"54"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No2"
	{
		"ControlName"		"Label"
		"fieldName"		"No2"
		"xpos"		"96"
		"ypos"		"82"
		"wide"		"13"
		"tall"		"18"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"2"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"zb3"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"zb3"
		"xpos"		"24"
		"ypos"		"138"
		"wide"		"64"
		"tall"		"54"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No3"
	{
		"ControlName"		"Label"
		"fieldName"		"No3"
		"xpos"		"27"
		"ypos"		"141"
		"wide"		"13"
		"tall"		"18"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"3"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"zb4"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"zb4"
		"xpos"		"93"
		"ypos"		"138"
		"wide"		"64"
		"tall"		"54"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No4"
	{
		"ControlName"		"Label"
		"fieldName"		"No4"
		"xpos"		"96"
		"ypos"		"141"
		"wide"		"13"
		"tall"		"18"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"4"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"zb5"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"zb5"
		"xpos"		"24"
		"ypos"		"197"
		"wide"		"64"
		"tall"		"54"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No5"
	{
		"ControlName"		"Label"
		"fieldName"		"No5"
		"xpos"		"27"
		"ypos"		"200"
		"wide"		"13"
		"tall"		"18"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"5"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"zb6"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"zb6"
		"xpos"		"93"
		"ypos"		"197"
		"wide"		"64"
		"tall"		"54"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No6"
	{
		"ControlName"		"Label"
		"fieldName"		"No6"
		"xpos"		"96"
		"ypos"		"200"
		"wide"		"13"
		"tall"		"18"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"6"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"zb7"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"zb7"
		"xpos"		"24"
		"ypos"		"256"
		"wide"		"64"
		"tall"		"54"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No7"
	{
		"ControlName"		"Label"
		"fieldName"		"No7"
		"xpos"		"27"
		"ypos"		"259"
		"wide"		"13"
		"tall"		"18"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"7"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"zb8"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"zb8"
		"xpos"		"93"
		"ypos"		"256"
		"wide"		"64"
		"tall"		"54"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No8"
	{
		"ControlName"		"Label"
		"fieldName"		"No8"
		"xpos"		"96"
		"ypos"		"259"
		"wide"		"13"
		"tall"		"18"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"8"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"zb9"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"zb9"
		"xpos"		"24"
		"ypos"		"315"
		"wide"		"64"
		"tall"		"54"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No9"
	{
		"ControlName"		"Label"
		"fieldName"		"No9"
		"xpos"		"27"
		"ypos"		"318"
		"wide"		"13"
		"tall"		"18"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"9"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"zb10"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"zb10"
		"xpos"		"93"
		"ypos"		"315"
		"wide"		"64"
		"tall"		"54"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No10"
	{
		"ControlName"		"Label"
		"fieldName"		"No10"
		"xpos"		"96"
		"ypos"		"318"
		"wide"		"13"
		"tall"		"18"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"0"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"Next"
	{
		"ControlName"		"Label"
		"fieldName"		"Label1"
		"xpos"		"24"
		"ypos"		"376"
		"wide"		"133"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_NextBuy"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
//	"Prev"
//	{
//		"ControlName"		"Label"
//		"fieldName"		"Label1"
//		"xpos"		"24"
//		"ypos"		"376"
//		"wide"		"133"
//		"tall"		"20"
//		"AutoResize"		"0"
//		"PinCorner"		"0"
//		"visible"		"1"
//		"enabled"		"1"
//		"tabPosition"		"0"
//		"paintbackground"		"1"
//		"labelText"		"#CSO_PrevBuy"
//		"textAlignment"		"east"
//		"dulltext"		"0"
//		"brighttext"		"0"
//		"wrap"		"0"
//	}
}
 