"classes/weaponInvenClass.res"
{
	"attrlabel0"
	{
		"ControlName"		"Label"
		"fieldName"		"attrlabel0"
		"xpos"		"5"
		"ypos"		"75"
		"wide"		"60"
		"tall"		"14"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"attrlabel1"
	{
		"ControlName"		"Label"
		"fieldName"		"attrlabel1"
		"xpos"		"5"
		"ypos"		"92"
		"wide"		"60"
		"tall"		"14"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"attrlabel2"
	{
		"ControlName"		"Label"
		"fieldName"		"attrlabel2"
		"xpos"		"5"
		"ypos"		"109"
		"wide"		"60"
		"tall"		"14"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"attrlabel3"
	{
		"ControlName"		"Label"
		"fieldName"		"attrlabel3"
		"xpos"		"5"
		"ypos"		"126"
		"wide"		"60"
		"tall"		"14"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"attrlabel4"
	{
		"ControlName"		"Label"
		"fieldName"		"attrlabel4"
		"xpos"		"5"
		"ypos"		"143"
		"wide"		"60"
		"tall"		"14"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"attrlabel5"
	{
		"ControlName"		"Label"
		"fieldName"		"attrlabel5"
		"xpos"		"5"
		"ypos"		"160"
		"wide"		"60"
		"tall"		"14"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"attrlabel6"
	{
		"ControlName"		"Label"
		"fieldName"		"attrlabel6"
		"xpos"		"5"
		"ypos"		"177"
		"wide"		"60"
		"tall"		"14"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"attrlabel7"
	{
		"ControlName"		"Label"
		"fieldName"		"attrlabel7"
		"xpos"		"5"
		"ypos"		"194"
		"wide"		"60"
		"tall"		"14"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"attrlabel8"
	{
		"ControlName"		"Label"
		"fieldName"		"attrlabel8"
		"xpos"		"5"
		"ypos"		"211"
		"wide"		"60"
		"tall"		"14"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"attrlabel9"
	{
		"ControlName"		"Label"
		"fieldName"		"attrlabel9"
		"xpos"		"5"
		"ypos"		"228"
		"wide"		"60"
		"tall"		"14"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"attr0"
	{
		"ControlName"		"Label"
		"fieldName"		"attr0"
		"xpos"		"75"
		"ypos"		"75"
		"wide"		"84"
		"tall"		"14"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"attr1"
	{
		"ControlName"		"Label"
		"fieldName"		"attr1"
		"xpos"		"75"
		"ypos"		"92"
		"wide"		"84"
		"tall"		"14"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"attr2"
	{
		"ControlName"		"Label"
		"fieldName"		"attr2"
		"xpos"		"75"
		"ypos"		"109"
		"wide"		"84"
		"tall"		"14"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"attr3"
	{
		"ControlName"		"Label"
		"fieldName"		"attr3"
		"xpos"		"75"
		"ypos"		"126"
		"wide"		"84"
		"tall"		"14"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"attr4"
	{
		"ControlName"		"Label"
		"fieldName"		"attr4"
		"xpos"		"75"
		"ypos"		"143"
		"wide"		"84"
		"tall"		"14"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"attr5"
	{
		"ControlName"		"Label"
		"fieldName"		"attr5"
		"xpos"		"75"
		"ypos"		"160"
		"wide"		"84"
		"tall"		"14"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"attr6"
	{
		"ControlName"		"Label"
		"fieldName"		"attr6"
		"xpos"		"75"
		"ypos"		"177"
		"wide"		"84"
		"tall"		"14"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"attr7"
	{
		"ControlName"		"Label"
		"fieldName"		"attr7"
		"xpos"		"75"
		"ypos"		"194"
		"wide"		"84"
		"tall"		"14"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"attr8"
	{
		"ControlName"		"Label"
		"fieldName"		"attr8"
		"xpos"		"75"
		"ypos"		"211"
		"wide"		"84"
		"tall"		"14"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"attr9"
	{
		"ControlName"		"Label"
		"fieldName"		"attr9"
		"xpos"		"75"
		"ypos"		"228"
		"wide"		"84"
		"tall"		"14"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"imageBG"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"imageBG"
		"xpos"		"5"
		"ypos"		"0"
		"wide"		"147"
		"tall"		"51"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"center"
		"image"			"resource/Control/Basket/basket_blank_slot"
		"scaleImage"	"1"
	}
	"classimage"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"classimage"
		"xpos"		"5"
		"ypos"		"0"
		"wide"		"147"
		"tall"		"51"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"west"
		"image"			""
		"scaleImage"	"1"
	}
	"DropWeaponButton"
	{
		"ControlName"		"Button"
		"fieldName"		"DropWeaponButton"
		"xpos"		"94"
		"ypos"		"53"
		"wide"		"60"
		"tall"		"21"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"center"
		"dulltext"		"1"
		"brighttext"		"0"
	}
}