"Popup_VoxelOutUI_ScrollMultiPanel"
{
	"ScrollMultiImageBG_1"
	{
		"ControlName"		"ThreePicsPanel"
		"fieldName"		"ScrollMultiImageBG_1"
		"xpos"		"14"
		"ypos"		"203"
		"wide"		"490"
		"tall"		"22"
		"zpos"		"2"
		"ThreePicsTgaPath"		"resource/Control/Button_List/3/Button_List"
		"visible"	"0"
		"IgnoreScheme"		"1"
		"scaleImage"		"1"
		"BgColor"		"5 5 5 150"
	}
	"ScrollMultiImageBG_2"
	{
		"ControlName"		"ThreePicsPanel"
		"fieldName"		"ScrollMultiImageBG_2"
		"xpos"		"14"
		"ypos"		"203"
		"wide"		"490"
		"tall"		"22"
		"zpos"		"2"
		"ThreePicsTgaPath"		"resource/Control/Button_List/3/Button_List"
		"visible"	"0"
		"IgnoreScheme"		"1"
		"scaleImage"		"1"
		"BgColor"		"5 5 5 150"
	}
	"ScrollMultiImageBG_3"
	{
		"ControlName"		"ThreePicsPanel"
		"fieldName"		"ScrollMultiImageBG_3"
		"xpos"		"14"
		"ypos"		"203"
		"wide"		"490"
		"tall"		"22"
		"zpos"		"2"
		"ThreePicsTgaPath"		"resource/Control/Button_List/3/Button_List"
		"visible"	"0"
		"IgnoreScheme"		"1"
		"scaleImage"		"1"
		"BgColor"		"5 5 5 150"
	}
	"ScrollMultiImageBG_4"
	{
		"ControlName"		"ThreePicsPanel"
		"fieldName"		"ScrollMultiImageBG_4"
		"xpos"		"14"
		"ypos"		"203"
		"wide"		"490"
		"tall"		"22"
		"zpos"		"2"
		"ThreePicsTgaPath"		"resource/Control/Button_List/3/Button_List"
		"visible"	"0"
		"IgnoreScheme"		"1"
		"scaleImage"		"1"
		"BgColor"		"5 5 5 150"
	}
}