"Shop_Item.res"
{
	"InventoryItemDlg"
	{
		"ControlName"		"CShopItemDlg"
		"fieldName"		"ShopItemDlg"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"554"
		"tall"		"585"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"settitlebarvisible"		"1"
		"title"		"untitle"
	}
	"TopTab"
	{
		"ControlName"		"Label"
		"fieldName"		"TopTab"
		"xpos"		"32"
		"ypos"		"0"
		"wide"		"80"
		"tall"		"21"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"ÀüÃ¼"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"VerticalTab"
	{
		"ControlName"		"Label"
		"fieldName"		"VerticalTab"
		"xpos"		"0"
		"ypos"		"21"
		"wide"		"32"
		"tall"		"98"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"HOT & NEW"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"ItemList"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"ItemItemList"
		"xpos"		"47"
		"ypos"		"24"
		"wide"		"502"
		"tall"		"625"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
}
 
