"Shop_ItemList"
{
	"ShopDlg"
	{
		"ControlName"		"CShopItemListDlg"
		"fieldName"		"ShopItemListDlg"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"554"
		"tall"		"651"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"settitlebarvisible"		"1"
		"title"		"untitle"
	}
	"Tab"
	{
		"ControlName"		"Label"
		"fieldName"		"Tab"
		"xpos"		"32"
		"ypos"		"0"
		"wide"		"80"
		"tall"		"21"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"ÀüÃ¼"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"VerticalTab"
	{
		"ControlName"		"Label"
		"fieldName"		"WidthTab"
		"xpos"		"0"
		"ypos"		"21"
		"wide"		"32"
		"tall"		"98"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"HOT & NEW"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"ItemListBg"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"ItemListBg"
		"xpos"		"32"
		"ypos"		"21"
		"wide"		"522"
		"tall"		"630"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"ItemList"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"ItemList"
		"xpos"		"47"
		"ypos"		"24"
		"wide"		"502"
		"tall"		"621"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
}
 
