"DisassembleItemList.res"
{
	"ItemDisassembleDlg"
	{
		"ControlName"		"CDisassembleItemListDlg"
		"fieldName"		"DisassembleItemListDlg"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"523"
		"tall"		"331"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"settitlebarvisible"		"1"
		"title"		"untitle"
	}
	"Slot1"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Slot1"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"165"
		"tall"		"99"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"image"			"resource/Itembox_s"
		"scaleImage"		"0"
	}
	"ItemBg1"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"ItemBg1"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"165"
		"tall"		"57"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Item1"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Item1"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"165"
		"tall"		"57"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"ItemName1"
	{
		"ControlName"		"Label"
		"fieldName"		"ItemName1"
		"xpos"		"5"
		"ypos"		"61"
		"wide"		"155"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"ItemPeriod1"
	{
		"ControlName"		"Label"
		"fieldName"		"ItemPeriod1"
		"xpos"		"5"
		"ypos"		"76"
		"wide"		"155"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Slot2"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Slot2"
		"xpos"		"179"
		"ypos"		"0"
		"wide"		"165"
		"tall"		"99"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"image"			"resource/Itembox_s"
		"scaleImage"		"0"
	}
	"ItemBg2"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"ItemBg2"
		"xpos"		"179"
		"ypos"		"0"
		"wide"		"165"
		"tall"		"57"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Item2"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Item2"
		"xpos"		"179"
		"ypos"		"0"
		"wide"		"165"
		"tall"		"57"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"ItemName2"
	{
		"ControlName"		"Label"
		"fieldName"		"ItemName2"
		"xpos"		"184"
		"ypos"		"61"
		"wide"		"155"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"ItemPeriod2"
	{
		"ControlName"		"Label"
		"fieldName"		"ItemPeriod2"
		"xpos"		"184"
		"ypos"		"76"
		"wide"		"155"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Slot3"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Slot3"
		"xpos"		"358"
		"ypos"		"0"
		"wide"		"165"
		"tall"		"99"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"image"			"resource/Itembox_s"
		"scaleImage"		"0"
	}
	"ItemBg3"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"ItemBg3"
		"xpos"		"358"
		"ypos"		"0"
		"wide"		"165"
		"tall"		"57"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Item3"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Item3"
		"xpos"		"358"
		"ypos"		"0"
		"wide"		"165"
		"tall"		"57"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"ItemName3"
	{
		"ControlName"		"Label"
		"fieldName"		"ItemName3"
		"xpos"		"363"
		"ypos"		"61"
		"wide"		"155"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"ItemPeriod3"
	{
		"ControlName"		"Label"
		"fieldName"		"ItemPeriod3"
		"xpos"		"363"
		"ypos"		"76"
		"wide"		"155"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Slot4"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Slot4"
		"xpos"		"0"
		"ypos"		"116"
		"wide"		"165"
		"tall"		"99"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"image"			"resource/Itembox_s"
		"scaleImage"		"0"
	}
	"ItemBg4"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"ItemBg4"
		"xpos"		"0"
		"ypos"		"116"
		"wide"		"165"
		"tall"		"57"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Item4"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Item4"
		"xpos"		"0"
		"ypos"		"116"
		"wide"		"165"
		"tall"		"57"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"ItemName4"
	{
		"ControlName"		"Label"
		"fieldName"		"ItemName4"
		"xpos"		"5"
		"ypos"		"177"
		"wide"		"155"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"ItemPeriod4"
	{
		"ControlName"		"Label"
		"fieldName"		"ItemPeriod4"
		"xpos"		"5"
		"ypos"		"192"
		"wide"		"155"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Slot5"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Slot5"
		"xpos"		"179"
		"ypos"		"116"
		"wide"		"165"
		"tall"		"99"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"image"			"resource/Itembox_s"
		"scaleImage"		"0"
	}
	"ItemBg5"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"ItemBg5"
		"xpos"		"179"
		"ypos"		"116"
		"wide"		"165"
		"tall"		"57"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Item5"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Item5"
		"xpos"		"179"
		"ypos"		"116"
		"wide"		"165"
		"tall"		"57"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"ItemName5"
	{
		"ControlName"		"Label"
		"fieldName"		"ItemName5"
		"xpos"		"184"
		"ypos"		"177"
		"wide"		"155"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"ItemPeriod5"
	{
		"ControlName"		"Label"
		"fieldName"		"ItemPeriod5"
		"xpos"		"184"
		"ypos"		"192"
		"wide"		"155"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Slot6"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Slot6"
		"xpos"		"358"
		"ypos"		"116"
		"wide"		"165"
		"tall"		"99"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"image"			"resource/Itembox_s"
		"scaleImage"		"0"
	}
	"ItemBg6"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"ItemBg6"
		"xpos"		"358"
		"ypos"		"116"
		"wide"		"165"
		"tall"		"57"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Item6"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Item6"
		"xpos"		"358"
		"ypos"		"116"
		"wide"		"165"
		"tall"		"57"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"ItemName6"
	{
		"ControlName"		"Label"
		"fieldName"		"ItemName6"
		"xpos"		"363"
		"ypos"		"177"
		"wide"		"155"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"ItemPeriod6"
	{
		"ControlName"		"Label"
		"fieldName"		"ItemPeriod6"
		"xpos"		"363"
		"ypos"		"192"
		"wide"		"155"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Slot7"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Slot7"
		"xpos"		"0"
		"ypos"		"232"
		"wide"		"165"
		"tall"		"99"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"image"			"resource/Itembox_s"
		"scaleImage"		"0"
	}
	"ItemBg7"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"ItemBg7"
		"xpos"		"0"
		"ypos"		"232"
		"wide"		"165"
		"tall"		"57"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Item7"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Item7"
		"xpos"		"0"
		"ypos"		"232"
		"wide"		"165"
		"tall"		"57"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"ItemName7"
	{
		"ControlName"		"Label"
		"fieldName"		"ItemName7"
		"xpos"		"5"
		"ypos"		"293"
		"wide"		"155"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"ItemPeriod7"
	{
		"ControlName"		"Label"
		"fieldName"		"ItemPeriod7"
		"xpos"		"5"
		"ypos"		"308"
		"wide"		"155"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Slot8"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Slot8"
		"xpos"		"179"
		"ypos"		"232"
		"wide"		"165"
		"tall"		"99"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"image"			"resource/Itembox_s"
		"scaleImage"		"0"
	}
	"ItemBg8"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"ItemBg8"
		"xpos"		"179"
		"ypos"		"232"
		"wide"		"165"
		"tall"		"57"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Item8"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Item8"
		"xpos"		"179"
		"ypos"		"232"
		"wide"		"165"
		"tall"		"57"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"ItemName8"
	{
		"ControlName"		"Label"
		"fieldName"		"ItemName8"
		"xpos"		"184"
		"ypos"		"293"
		"wide"		"155"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"ItemPeriod8"
	{
		"ControlName"		"Label"
		"fieldName"		"ItemPeriod8"
		"xpos"		"184"
		"ypos"		"308"
		"wide"		"155"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Slot9"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Slot9"
		"xpos"		"358"
		"ypos"		"232"
		"wide"		"165"
		"tall"		"99"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"image"			"resource/Itembox_s"
		"scaleImage"		"0"
	}
	"ItemBg9"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"ItemBg9"
		"xpos"		"358"
		"ypos"		"232"
		"wide"		"165"
		"tall"		"57"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Item9"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Item9"
		"xpos"		"358"
		"ypos"		"232"
		"wide"		"165"
		"tall"		"57"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"ItemName9"
	{
		"ControlName"		"Label"
		"fieldName"		"ItemName9"
		"xpos"		"363"
		"ypos"		"293"
		"wide"		"155"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"ItemPeriod9"
	{
		"ControlName"		"Label"
		"fieldName"		"ItemPeriod9"
		"xpos"		"363"
		"ypos"		"308"
		"wide"		"155"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
}
