"InGameParticleTester.res"
{	
	"InGameParticleTesterDlg"
	{
		"ControlName"	"Panel"
		"fieldName"		"InGameParticleTesterDlg"
		"xpos"			"21"
		"ypos"			"30"
		"wide"			"610"
		"tall"			"426"
		"AutoResize"	"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"settitlebarvisible"		"1"
		"title"		""
	}

	"TitleLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"TitleLabel"
		"xpos"		"25"
		"ypos"		"12"
		"wide"		"553"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Particle_Tester_Label"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"ForceTextColor"		"192 192 192 255"
		"EnableForceTextColor"	"1"
	}

	"NameLabel0"
	{
		"ControlName"		"Label"
		"fieldName"		"NameLabel0"
		"xpos"		"20"
		"ypos"		"65"
		"wide"		"114"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Particle_Tester_Name_Label0"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"ForceTextColor"		"255 255 255 255"
		"EnableForceTextColor"	"1"
	}

	"NameLabel1"
	{
		"ControlName"		"Label"
		"fieldName"		"NameLabel1"
		"xpos"		"20"
		"ypos"		"90"
		"wide"		"114"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Particle_Tester_Name_Label1"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"ForceTextColor"		"255 255 255 255"
		"EnableForceTextColor"	"1"
	}

	"NameLabel2"
	{
		"ControlName"		"Label"
		"fieldName"		"NameLabel2"
		"xpos"		"20"
		"ypos"		"115"
		"wide"		"114"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Particle_Tester_Name_Label2"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"ForceTextColor"		"255 255 255 255"
		"EnableForceTextColor"	"1"
	}

	"NameLabel3"
	{
		"ControlName"		"Label"
		"fieldName"		"NameLabel3"
		"xpos"		"20"
		"ypos"		"140"
		"wide"		"114"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Particle_Tester_Name_Label3"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"ForceTextColor"		"255 255 255 255"
		"EnableForceTextColor"	"1"
	}

	"NameLabel4"
	{
		"ControlName"		"Label"
		"fieldName"		"NameLabel4"
		"xpos"		"20"
		"ypos"		"165"
		"wide"		"114"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Particle_Tester_Name_Label4"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"ForceTextColor"		"255 255 255 255"
		"EnableForceTextColor"	"1"
	}
	
	"NameLabel5"
	{
		"ControlName"		"Label"
		"fieldName"		"NameLabel5"
		"xpos"		"20"
		"ypos"		"190"
		"wide"		"114"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Particle_Tester_Name_Label5"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"ForceTextColor"		"255 255 255 255"
		"EnableForceTextColor"	"1"
	}
	
	"NameLabel6"
	{
		"ControlName"		"Label"
		"fieldName"		"NameLabel6"
		"xpos"		"20"
		"ypos"		"215"
		"wide"		"114"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Particle_Tester_Name_Label6"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"ForceTextColor"		"255 255 255 255"
		"EnableForceTextColor"	"1"
	}
	
	"NameLabel6-1"
	{
		"ControlName"		"Label"
		"fieldName"		"NameLabel6-1"
		"xpos"		"130"
		"ypos"		"215"
		"wide"		"20"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"R"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"ForceTextColor"		"255 0 0 255"
		"EnableForceTextColor"	"1"
	}
	
	"NameLabel6-2"
	{
		"ControlName"		"Label"
		"fieldName"		"NameLabel6-2"
		"xpos"		"180"
		"ypos"		"215"
		"wide"		"20"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"G"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"ForceTextColor"		"0 255 0 255"
		"EnableForceTextColor"	"1"
	}

	"NameLabel6-3"
	{
		"ControlName"		"Label"
		"fieldName"		"NameLabel6-3"
		"xpos"		"230"
		"ypos"		"215"
		"wide"		"20"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"B"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"ForceTextColor"		"0 0 255 255"
		"EnableForceTextColor"	"1"
	}

	"NameLabel7"
	{
		"ControlName"		"Label"
		"fieldName"		"NameLabel7"
		"xpos"		"20"
		"ypos"		"240"
		"wide"		"114"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Particle_Tester_Name_Label7"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"ForceTextColor"		"255 255 255 255"
		"EnableForceTextColor"	"1"
	}
	
	"NameLabel8"
	{
		"ControlName"		"Label"
		"fieldName"		"NameLabel8"
		"xpos"		"300"
		"ypos"		"65"
		"wide"		"114"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Particle_Tester_Name_Label8"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"ForceTextColor"		"255 255 255 255"
		"EnableForceTextColor"	"1"
	}

	"NameLabel9"
	{
		"ControlName"		"Label"
		"fieldName"		"NameLabel9"
		"xpos"		"300"
		"ypos"		"90"
		"wide"		"114"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Particle_Tester_Name_Label9"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"ForceTextColor"		"255 255 255 255"
		"EnableForceTextColor"	"1"
	}

	"NameLabel10"
	{
		"ControlName"		"Label"
		"fieldName"		"NameLabel10"
		"xpos"		"300"
		"ypos"		"115"
		"wide"		"114"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Particle_Tester_Name_Label10"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"ForceTextColor"		"255 255 255 255"
		"EnableForceTextColor"	"1"
	}

	"NameLabel11"
	{
		"ControlName"		"Label"
		"fieldName"		"NameLabel11"
		"xpos"		"300"
		"ypos"		"140"
		"wide"		"114"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Particle_Tester_Name_Label11"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"ForceTextColor"		"255 255 255 255"
		"EnableForceTextColor"	"1"
	}

	"NameLabel12"
	{
		"ControlName"		"Label"
		"fieldName"		"NameLabel12"
		"xpos"		"300"
		"ypos"		"165"
		"wide"		"114"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Particle_Tester_Name_Label12"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"ForceTextColor"		"255 255 255 255"
		"EnableForceTextColor"	"1"
	}

	"NameLabel13"
	{
		"ControlName"		"Label"
		"fieldName"		"NameLabel13"
		"xpos"		"300"
		"ypos"		"190"
		"wide"		"114"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Particle_Tester_Name_Label13"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"ForceTextColor"		"255 255 255 255"
		"EnableForceTextColor"	"1"
	}
	
	"InfoText0"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"InfoText0"
		"xpos"		"130"
		"ypos"		"65"
		"wide"		"150"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"127"
		"NumericInputOnly"		"0"
		"unicode"		"1"
	}
	
	"InfoText1"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"InfoText1"
		"xpos"		"130"
		"ypos"		"90"
		"wide"		"150"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"18"
		"NumericInputOnly"		"1"
		"unicode"		"1"
	}

	"InfoText2"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"InfoText2"
		"xpos"		"130"
		"ypos"		"115"
		"wide"		"150"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"18"
		"NumericInputOnly"		"1"
		"unicode"		"1"
	}

	"InfoText3"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"InfoText3"
		"xpos"		"130"
		"ypos"		"140"
		"wide"		"150"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"18"
		"NumericInputOnly"		"1"
		"unicode"		"1"
	}

	"InfoText4"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"InfoText4"
		"xpos"		"130"
		"ypos"		"165"
		"wide"		"150"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"18"
		"NumericInputOnly"		"1"
		"unicode"		"1"
	}

	"InfoText5"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"InfoText5"
		"xpos"		"130"
		"ypos"		"190"
		"wide"		"150"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"18"
		"NumericInputOnly"		"1"
		"unicode"		"1"
	}
	
	"InfoText6"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"InfoText6"
		"xpos"		"145"
		"ypos"		"215"
		"wide"		"30"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"3"
		"NumericInputOnly"		"1"
		"unicode"		"1"
	}
	
	"InfoText7"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"InfoText7"
		"xpos"		"195"
		"ypos"		"215"
		"wide"		"30"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"3"
		"NumericInputOnly"		"1"
		"unicode"		"1"
	}
		
	"InfoText8"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"InfoText8"
		"xpos"		"245"
		"ypos"		"215"
		"wide"		"30"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"3"
		"NumericInputOnly"		"1"
		"unicode"		"1"
	}
	
	"InfoText9"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"InfoText9"
		"xpos"		"130"
		"ypos"		"240"
		"wide"		"150"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"18"
		"NumericInputOnly"		"1"
		"unicode"		"1"
	}
	
	"InfoText10"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"InfoText10"
		"xpos"		"410"
		"ypos"		"65"
		"wide"		"150"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"18"
		"NumericInputOnly"		"1"
		"unicode"		"1"
	}

	"InfoText11"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"InfoText11"
		"xpos"		"410"
		"ypos"		"90"
		"wide"		"150"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"18"
		"NumericInputOnly"		"1"
		"unicode"		"1"
	}

	"InfoText12"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"InfoText12"
		"xpos"		"410"
		"ypos"		"115"
		"wide"		"150"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"18"
		"NumericInputOnly"		"1"
		"unicode"		"1"
	}

	"InfoText13"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"InfoText13"
		"xpos"		"410"
		"ypos"		"140"
		"wide"		"150"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"18"
		"NumericInputOnly"		"1"
		"unicode"		"1"
	}
	
	"RenderingMode"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"RenderingMode"
		"xpos"		"410"
		"ypos"		"165"
		"wide"		"150"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}

	"CheckBtn0"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckBtn0"
		"xpos"		"410"
		"ypos"		"190"
		"wide"		"150"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"Animate"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	
	"CheckBtn1"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckBtn1"
		"xpos"		"410"
		"ypos"		"215"
		"wide"		"150"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"Collidekill"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"CheckBtn2"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckBtn2"
		"xpos"		"410"
		"ypos"		"240"
		"wide"		"150"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"Start on"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}

	"CheckBtn3"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckBtn3"
		"xpos"		"410"
		"ypos"		"265"
		"wide"		"150"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"Collideworld"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}

	"CreateBtn"
	{
		"ControlName"		"Button"
		"fieldName"		"CreateBtn"
		"xpos"		"300"
		"ypos"		"350"
		"wide"		"120"
		"tall"		"35"
		"AutoResize"	"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Particle_Tester_CreateBtn"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}

	"CloseBtn"
	{
		"ControlName"		"Button"
		"fieldName"		"CloseBtn"
		"xpos"		"450"
		"ypos"		"350"
		"wide"		"120"
		"tall"		"35"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Particle_Tester_CloseBtn"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
}