"Popup_CustomStart_Ver2.res"
{
	"CustomStartDlg"
	{
		"ControlName"		"CCustomStartDlgV2"
		"fieldName"		"CustomStartDlg"
		"xpos"		"68"
		"ypos"		"154"
		"wide"		"898"
		"tall"		"490"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"settitlebarvisible"		"1"
		"title"		"#CSO_CustomStart_Label"
	}
	"HotMapBg1"
	{
		"ControlName"		"CSignalRoundPanel"
		"fieldName"		"HotMapBg1"
		"xpos"		"28"
		"ypos"		"44"
		"wide"		"200"
		"tall"		"144"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"HotMap1"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HotMap1"
		"xpos"		"28"
		"ypos"		"44"
		"wide"		"200"
		"tall"		"97"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
	}
	"Icon1"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Icon1"
		"xpos"		"28"
		"ypos"		"44"
		"wide"		"59"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"image"			"resource/Bulletin/Hot"
		"scaleImage"		"0"
	}
	"ModeLabel1"
	{
		"ControlName"		"Label"
		"fieldName"		"ModeLabel1"
		"xpos"		"34"
		"ypos"		"146"
		"wide"		"188"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"kaka"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"MapLabel1"
	{
		"ControlName"		"Label"
		"fieldName"		"MapLabel1"
		"xpos"		"34"
		"ypos"		"166"
		"wide"		"188"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"kaka"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"HotMapBg2"
	{
		"ControlName"		"CSignalRoundPanel"
		"fieldName"		"HotMapBg2"
		"xpos"		"239"
		"ypos"		"44"
		"wide"		"200"
		"tall"		"144"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"HotMap2"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HotMap2"
		"xpos"		"239"
		"ypos"		"44"
		"wide"		"200"
		"tall"		"97"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
	}
	"Icon2"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Icon2"
		"xpos"		"239"
		"ypos"		"44"
		"wide"		"59"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"image"			"resource/Bulletin/Hot"
		"scaleImage"		"0"
	}
	"ModeLabel2"
	{
		"ControlName"		"Label"
		"fieldName"		"ModeLabel2"
		"xpos"		"245"
		"ypos"		"146"
		"wide"		"188"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"kaka"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"MapLabel2"
	{
		"ControlName"		"Label"
		"fieldName"		"MapLabel2"
		"xpos"		"245"
		"ypos"		"166"
		"wide"		"188"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"kaka"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"HotMapBg3"
	{
		"ControlName"		"CSignalRoundPanel"
		"fieldName"		"HotMapBg3"
		"xpos"		"450"
		"ypos"		"44"
		"wide"		"200"
		"tall"		"144"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"HotMap3"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HotMap3"
		"xpos"		"450"
		"ypos"		"44"
		"wide"		"200"
		"tall"		"97"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
	}
	"Icon3"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Icon3"
		"xpos"		"450"
		"ypos"		"44"
		"wide"		"59"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"image"			"resource/Bulletin/Hot"
		"scaleImage"		"0"
	}
	"ModeLabel3"
	{
		"ControlName"		"Label"
		"fieldName"		"ModeLabel3"
		"xpos"		"456"
		"ypos"		"146"
		"wide"		"188"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"kaka"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"MapLabel3"
	{
		"ControlName"		"Label"
		"fieldName"		"MapLabel3"
		"xpos"		"456"
		"ypos"		"166"
		"wide"		"188"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"kaka"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"HotMapBg4"
	{
		"ControlName"		"CSignalRoundPanel"
		"fieldName"		"HotMapBg4"
		"xpos"		"661"
		"ypos"		"44"
		"wide"		"200"
		"tall"		"144"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"HotMap4"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HotMap4"
		"xpos"		"661"
		"ypos"		"44"
		"wide"		"200"
		"tall"		"97"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
	}
	"Icon4"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Icon4"
		"xpos"		"661"
		"ypos"		"44"
		"wide"		"59"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"image"			"resource/Bulletin/Hot"
		"scaleImage"		"0"
	}
	"ModeLabel4"
	{
		"ControlName"		"Label"
		"fieldName"		"ModeLabel4"
		"xpos"		"667"
		"ypos"		"146"
		"wide"		"188"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"kaka"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"MapLabel4"
	{
		"ControlName"		"Label"
		"fieldName"		"MapLabel4"
		"xpos"		"667"
		"ypos"		"166"
		"wide"		"188"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"kaka"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"CustomStartBg"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"CustomStartBg"
		"xpos"		"15"
		"ypos"		"207"
		"wide"		"858"
		"tall"		"257"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"1"
		"zpos"				"-1"
	}
	"ServerLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ServerLabel"
		"xpos"		"25"
		"ypos"		"219"
		"wide"		"92"
		"tall"		"23"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Server_Lable"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Server"
	{
		"ControlName"		"GameOptionComboBox"
		"fieldName"		"Server"
		"xpos"		"122"
		"ypos"		"219"
		"wide"		"400"
		"tall"		"23"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"1st"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"1st"
		"xpos"		"25"
		"ypos"		"254"
		"wide"		"36"
		"tall"		"48"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"		"resource/QuickStart/custom1st"
	}	
	"1stModeBg"
	{
		"ControlName"		"CSignalRoundPanel"
		"fieldName"		"1stModeBg"
		"xpos"		"66"
		"ypos"		"254"
		"wide"		"214"
		"tall"		"48"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}	
	"1stModeIcon"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"1stModeIcon"
		"xpos"		"66"
		"ypos"		"254"
		"wide"		"48"
		"tall"		"48"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"1stModeLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"1stModeLabel"
		"xpos"		"124"
		"ypos"		"265"
		"wide"		"146"
		"tall"		"26"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"1stMapBg"
	{
		"ControlName"		"CSignalRoundPanel"
		"fieldName"		"1stMapBg"
		"xpos"		"285"
		"ypos"		"254"
		"wide"		"292"
		"tall"		"48"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}	
	"1stMapIcon"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"1stMapIcon"
		"xpos"		"285"
		"ypos"		"254"
		"wide"		"99"
		"tall"		"48"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
	}
	"1stMapLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"1stMapLabel"
		"xpos"		"394"
		"ypos"		"268"
		"wide"		"173"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}	
	"2nd"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"2nd"
		"xpos"		"25"
		"ypos"		"308"
		"wide"		"36"
		"tall"		"48"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"		"resource/QuickStart/custom2nd"
	}	
	"2ndModeBg"
	{
		"ControlName"		"CSignalRoundPanel"
		"fieldName"		"2ndModeBg"
		"xpos"		"66"
		"ypos"		"308"
		"wide"		"214"
		"tall"		"48"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}	
	"2ndModeIcon"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"2ndModeIcon"
		"xpos"		"66"
		"ypos"		"308"
		"wide"		"48"
		"tall"		"48"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"2ndModeLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"2ndModeLabel"
		"xpos"		"124"
		"ypos"		"319"
		"wide"		"146"
		"tall"		"26"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"2ndMapBg"
	{
		"ControlName"		"CSignalRoundPanel"
		"fieldName"		"2ndMapBg"
		"xpos"		"285"
		"ypos"		"308"
		"wide"		"292"
		"tall"		"48"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}	
	"2ndMapIcon"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"2ndMapIcon"
		"xpos"		"285"
		"ypos"		"308"
		"wide"		"99"
		"tall"		"48"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
	}
	"2ndMapLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"2ndMapLabel"
		"xpos"		"394"
		"ypos"		"322"
		"wide"		"173"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}	
	"3rd"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"3rd"
		"xpos"		"25"
		"ypos"		"362"
		"wide"		"36"
		"tall"		"48"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"		"resource/QuickStart/custom3rd"
	}	
	"3rdModeBg"
	{
		"ControlName"		"CSignalRoundPanel"
		"fieldName"		"3rdModeBg"
		"xpos"		"66"
		"ypos"		"362"
		"wide"		"214"
		"tall"		"48"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}	
	"3rdModeIcon"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"3rdModeIcon"
		"xpos"		"66"
		"ypos"		"362"
		"wide"		"48"
		"tall"		"48"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"3rdModeLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"3rdModeLabel"
		"xpos"		"124"
		"ypos"		"373"
		"wide"		"146"
		"tall"		"26"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"3rdMapBg"
	{
		"ControlName"		"CSignalRoundPanel"
		"fieldName"		"3rdMapBg"
		"xpos"		"285"
		"ypos"		"362"
		"wide"		"292"
		"tall"		"48"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}	
	"3rdMapIcon"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"3rdMapIcon"
		"xpos"		"285"
		"ypos"		"362"
		"wide"		"99"
		"tall"		"48"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
	}
	"3rdMapLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"3rdMapLabel"
		"xpos"		"394"
		"ypos"		"376"
		"wide"		"173"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"SetModeBg"
	{
		"ControlName"		"CRoundPanel"
		"fieldName"		"SetModeBg"
		"xpos"		"584"
		"ypos"		"254"
		"wide"		"279"
		"tall"		"156"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"SetModeLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"SetModeLabel"
		"xpos"		"594"
		"ypos"		"269"
		"wide"		"259"
		"tall"		"23"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_SetMode_Label"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default16"
		"wrap"		"0"
	}
	"WeaponRestrictLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"WeaponRestrictLabel"
		"xpos"		"594"
		"ypos"		"308"
		"wide"		"96"
		"tall"		"23"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_WeaponLimit_Lable2"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"WeaponRestrict"
	{
		"ControlName"		"GameOptionComboBox"
		"fieldName"		"WeaponRestrict"
		"xpos"		"695"
		"ypos"		"308"
		"wide"		"158"
		"tall"		"23"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"MapSearch"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"MapSearch"
		"xpos"		"592"
		"ypos"		"350"
		"wide"		"261"
		"tall"		"23"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"0"
		"labelText"		"#CSO_MapSearch_Btn"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"WaitingRoomSearch"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"WaitingRoomSearch"
		"xpos"		"592"
		"ypos"		"376"
		"wide"		"261"
		"tall"		"23"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"0"
		"labelText"		"#CSO_WaitingRoomSearch_Btn"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"ResetBtn"
	{
		"ControlName"		"Button"
		"fieldName"		"ResetBtn"
		"xpos"		"409"
		"ypos"		"423"
		"wide"		"98"
		"tall"		"32"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Initialize"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"1"
	}
	"CancelBtn"
	{
		"ControlName"		"Button"
		"fieldName"		"CancelBtn"
		"xpos"		"513"
		"ypos"		"423"
		"wide"		"98"
		"tall"		"32"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_ClosePopup"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"1"
	}
	"CustomStartBtn"
	{
		"ControlName"		"ThreePicsButton"
		"fieldName"		"CustomStartBtn"
		"xpos"		"633"
		"ypos"		"423"
		"wide"		"178"
		"tall"		"32"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_CustomStart_Btn"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"1"
	}
}

