"PokerCardDeckDlg.res"
{
	"PokerCardDeckDlg"
	{
		"ControlName"		"CPokerCardDeckDlg"
		"fieldName"		"PokerCardDeckDlg"
		"xpos"		"142"
		"ypos"		"148"
		"wide"		"750"
		"tall"		"420"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"settitlebarvisible"		"1"
		"title"		"#CSO_POKER_EVT_TITLE"
	}
	"CardBg"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"CardBg"
		"xpos"		"15"
		"ypos"		"42"
		"wide"		"711"
		"tall"		"205"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"1"
	}
	"Card1"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Card1"
		"xpos"		"23"
		"ypos"		"50"
		"wide"		"96"
		"tall"		"136"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Bink1"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Bink1"
		"xpos"		"23"
		"ypos"		"50"
		"wide"		"96"
		"tall"		"146"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No1Up"
	{
		"ControlName"		"Label"
		"fieldName"		"No1Up"
		"xpos"		"24"
		"ypos"		"54"
		"wide"		"18"
		"tall"		"15"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default16"
		"wrap"		"0"
	}
	"Icon1Up"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Icon1Up"
		"xpos"		"26"
		"ypos"		"72"
		"wide"		"14"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No1Down"
	{
		"ControlName"		"Label"
		"fieldName"		"No1Down"
		"xpos"		"99"
		"ypos"		"166"
		"wide"		"18"
		"tall"		"15"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default16"
		"wrap"		"0"
	}
	"Icon1Down"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Icon1Down"
		"xpos"		"101"
		"ypos"		"149"
		"wide"		"14"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Card2"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Card2"
		"xpos"		"123"
		"ypos"		"50"
		"wide"		"96"
		"tall"		"136"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Bink2"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Bink2"
		"xpos"		"123"
		"ypos"		"50"
		"wide"		"96"
		"tall"		"146"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No2Up"
	{
		"ControlName"		"Label"
		"fieldName"		"No2Up"
		"xpos"		"124"
		"ypos"		"54"
		"wide"		"18"
		"tall"		"15"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default16"
		"wrap"		"0"
	}
	"Icon2Up"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Icon2Up"
		"xpos"		"126"
		"ypos"		"72"
		"wide"		"14"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No2Down"
	{
		"ControlName"		"Label"
		"fieldName"		"No2Down"
		"xpos"		"199"
		"ypos"		"166"
		"wide"		"18"
		"tall"		"15"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default16"
		"wrap"		"0"
	}
	"Icon2Down"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Icon2Down"
		"xpos"		"201"
		"ypos"		"149"
		"wide"		"14"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Card3"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Card3"
		"xpos"		"223"
		"ypos"		"50"
		"wide"		"96"
		"tall"		"136"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Bink3"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Bink3"
		"xpos"		"223"
		"ypos"		"50"
		"wide"		"96"
		"tall"		"146"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No3Up"
	{
		"ControlName"		"Label"
		"fieldName"		"No3Up"
		"xpos"		"224"
		"ypos"		"54"
		"wide"		"18"
		"tall"		"15"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default16"
		"wrap"		"0"
	}
	"Icon3Up"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Icon3Up"
		"xpos"		"226"
		"ypos"		"72"
		"wide"		"14"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No3Down"
	{
		"ControlName"		"Label"
		"fieldName"		"No3Down"
		"xpos"		"299"
		"ypos"		"166"
		"wide"		"18"
		"tall"		"15"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default16"
		"wrap"		"0"
	}
	"Icon3Down"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Icon3Down"
		"xpos"		"301"
		"ypos"		"149"
		"wide"		"14"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Card4"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Card4"
		"xpos"		"323"
		"ypos"		"50"
		"wide"		"96"
		"tall"		"136"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Bink4"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Bink4"
		"xpos"		"323"
		"ypos"		"50"
		"wide"		"96"
		"tall"		"146"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No4Up"
	{
		"ControlName"		"Label"
		"fieldName"		"No4Up"
		"xpos"		"324"
		"ypos"		"54"
		"wide"		"18"
		"tall"		"15"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default16"
		"wrap"		"0"
	}
	"Icon4Up"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Icon4Up"
		"xpos"		"326"
		"ypos"		"72"
		"wide"		"14"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No4Down"
	{
		"ControlName"		"Label"
		"fieldName"		"No4Down"
		"xpos"		"399"
		"ypos"		"166"
		"wide"		"18"
		"tall"		"15"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default16"
		"wrap"		"0"
	}
	"Icon4Down"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Icon4Down"
		"xpos"		"401"
		"ypos"		"149"
		"wide"		"14"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Card5"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Card5"
		"xpos"		"423"
		"ypos"		"50"
		"wide"		"96"
		"tall"		"136"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Bink5"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Bink5"
		"xpos"		"423"
		"ypos"		"50"
		"wide"		"96"
		"tall"		"146"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No5Up"
	{
		"ControlName"		"Label"
		"fieldName"		"No5Up"
		"xpos"		"424"
		"ypos"		"54"
		"wide"		"18"
		"tall"		"15"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default16"
		"wrap"		"0"
	}
	"Icon5Up"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Icon5Up"
		"xpos"		"426"
		"ypos"		"72"
		"wide"		"14"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No5Down"
	{
		"ControlName"		"Label"
		"fieldName"		"No5Down"
		"xpos"		"499"
		"ypos"		"166"
		"wide"		"18"
		"tall"		"15"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default16"
		"wrap"		"0"
	}
	"Icon5Down"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Icon5Down"
		"xpos"		"501"
		"ypos"		"149"
		"wide"		"14"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Card6"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Card6"
		"xpos"		"523"
		"ypos"		"50"
		"wide"		"96"
		"tall"		"136"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Bink6"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Bink6"
		"xpos"		"523"
		"ypos"		"50"
		"wide"		"96"
		"tall"		"146"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No6Up"
	{
		"ControlName"		"Label"
		"fieldName"		"No6Up"
		"xpos"		"524"
		"ypos"		"54"
		"wide"		"18"
		"tall"		"15"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default16"
		"wrap"		"0"
	}
	"Icon6Up"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Icon6Up"
		"xpos"		"526"
		"ypos"		"72"
		"wide"		"14"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No6Down"
	{
		"ControlName"		"Label"
		"fieldName"		"No6Down"
		"xpos"		"599"
		"ypos"		"166"
		"wide"		"18"
		"tall"		"15"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default16"
		"wrap"		"0"
	}
	"Icon6Down"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Icon6Down"
		"xpos"		"601"
		"ypos"		"149"
		"wide"		"14"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Card7"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Card7"
		"xpos"		"623"
		"ypos"		"50"
		"wide"		"96"
		"tall"		"136"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Bink7"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Bink7"
		"xpos"		"623"
		"ypos"		"50"
		"wide"		"96"
		"tall"		"146"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No7Up"
	{
		"ControlName"		"Label"
		"fieldName"		"No7Up"
		"xpos"		"624"
		"ypos"		"54"
		"wide"		"18"
		"tall"		"15"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default16"
		"wrap"		"0"
	}
	"Icon7Up"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Icon7Up"
		"xpos"		"626"
		"ypos"		"72"
		"wide"		"14"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"No7Down"
	{
		"ControlName"		"Label"
		"fieldName"		"No7Down"
		"xpos"		"699"
		"ypos"		"166"
		"wide"		"18"
		"tall"		"15"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default16"
		"wrap"		"0"
	}
	"Icon7Down"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Icon7Down"
		"xpos"		"701"
		"ypos"		"149"
		"wide"		"14"
		"tall"		"14"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"btn_Card_Open"
	{
		"ControlName"		"Button"
		"fieldName"		"btn_Card_Open"
		"xpos"		"60"
		"ypos"		"203"
		"wide"		"148"
		"tall"		"32"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_CardOpen_Btn"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"btn_Card_Reset"
	{
		"ControlName"		"Button"
		"fieldName"		"btn_Card_Reset"
		"xpos"		"215"
		"ypos"		"203"
		"wide"		"148"
		"tall"		"32"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_CardReset_Btn"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"btn_Card_Delete"
	{
		"ControlName"		"Button"
		"fieldName"		"btn_Card_Delete"
		"xpos"		"370"
		"ypos"		"203"
		"wide"		"148"
		"tall"		"32"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_CardDelete_Btn"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"btn_Card_Send"
	{
		"ControlName"		"Button"
		"fieldName"		"btn_Card_Send"
		"xpos"		"525"
		"ypos"		"203"
		"wide"		"148"
		"tall"		"32"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_CardSend_Btn"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"InfoMsg"
	{
		"ControlName"		"Label"
		"fieldName"		"InfoMsg"
		"xpos"		"22"
		"ypos"		"260"
		"wide"		"283"
		"tall"		"131"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_POKER_EVT_SCRIPT"
		"textAlignment"		"north-west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"TimeTextBg"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"TimeTextBg"
		"xpos"		"317"
		"ypos"		"260"
		"wide"		"177"
		"tall"		"41"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"TimeText"
	{
		"ControlName"		"Label"
		"fieldName"		"TimeText"
		"xpos"		"331"
		"ypos"		"265"
		"wide"		"149"
		"tall"		"31"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_POKER_EVT_Time"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"TimeBg"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"TimeBg"
		"xpos"		"496"
		"ypos"		"260"
		"wide"		"230"
		"tall"		"41"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Time"
	{
		"ControlName"		"Label"
		"fieldName"		"Time"
		"xpos"		"505"
		"ypos"		"265"
		"wide"		"212"
		"tall"		"31"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"OpenCardTextBg"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"OpenCardTextBg"
		"xpos"		"317"
		"ypos"		"305"
		"wide"		"177"
		"tall"		"41"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"OpenCardText"
	{
		"ControlName"		"Label"
		"fieldName"		"OpenCardText"
		"xpos"		"331"
		"ypos"		"310"
		"wide"		"149"
		"tall"		"31"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_POKER_EVT_OpenCard"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"OpenCardBg"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"OpenCardBg"
		"xpos"		"496"
		"ypos"		"305"
		"wide"		"230"
		"tall"		"41"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"OpenCard"
	{
		"ControlName"		"Label"
		"fieldName"		"OpenCard"
		"xpos"		"505"
		"ypos"		"310"
		"wide"		"212"
		"tall"		"31"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"SelectCardTextBg"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"SelectCardTextBg"
		"xpos"		"317"
		"ypos"		"350"
		"wide"		"177"
		"tall"		"41"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"SelectCardText"
	{
		"ControlName"		"Label"
		"fieldName"		"SelectCardText"
		"xpos"		"331"
		"ypos"		"355"
		"wide"		"149"
		"tall"		"31"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_POKER_EVT_SelectCard"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"SelectCardBg"
	{
		"ControlName"		"RoundPanel"
		"fieldName"		"SelectCardBg"
		"xpos"		"496"
		"ypos"		"350"
		"wide"		"230"
		"tall"		"41"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"SelectCard"
	{
		"ControlName"		"Label"
		"fieldName"		"SelectCard"
		"xpos"		"505"
		"ypos"		"355"
		"wide"		"212"
		"tall"		"31"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	
}
