"Popup_PokerEventResult.res"
{
	"PokerEventResultPopupDlg"
	{
		"ControlName"		"CPokerEventResultPopupDlg"
		"fieldName"		"PokerEventResultPopupDlg"
		"xpos"		"225"
		"ypos"		"176"
		"wide"		"585"
		"tall"		"364"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"settitlebarvisible"		"1"
		"title"		"#CSO_POKER_EVT_ResultTitle"
	}
	"Grade1"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Grade1"
		"xpos"		"15"
		"ypos"		"42"
		"wide"		"110"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"1"
	}
	"Grade1Label"
	{
		"ControlName"		"Label"
		"fieldName"		"Grade1Label"
		"xpos"		"22"
		"ypos"		"42"
		"wide"		"96"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_POKER_EVT_Grade1"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Nick1"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Nick1"
		"xpos"		"128"
		"ypos"		"42"
		"wide"		"144"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"1"
	}
	"Nick1Label"
	{
		"ControlName"		"Label"
		"fieldName"		"Nick1Label"
		"xpos"		"135"
		"ypos"		"42"
		"wide"		"130"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Score1"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Score1"
		"xpos"		"276"
		"ypos"		"42"
		"wide"		"284"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"1"
	}
	"Score1Label"
	{
		"ControlName"		"Label"
		"fieldName"		"Score1Label"
		"xpos"		"283"
		"ypos"		"42"
		"wide"		"270"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Grade2"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Grade2"
		"xpos"		"15"
		"ypos"		"77"
		"wide"		"110"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"1"
	}
	"Grade2Label"
	{
		"ControlName"		"Label"
		"fieldName"		"Grade2Label"
		"xpos"		"22"
		"ypos"		"77"
		"wide"		"96"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_POKER_EVT_Grade2"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Nick2"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Nick2"
		"xpos"		"128"
		"ypos"		"77"
		"wide"		"144"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"1"
	}
	"Nick2Label"
	{
		"ControlName"		"Label"
		"fieldName"		"Nick2Label"
		"xpos"		"135"
		"ypos"		"77"
		"wide"		"130"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Score2"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Score2"
		"xpos"		"276"
		"ypos"		"77"
		"wide"		"284"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"1"
	}
	"Score2Label"
	{
		"ControlName"		"Label"
		"fieldName"		"Score2Label"
		"xpos"		"283"
		"ypos"		"77"
		"wide"		"270"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Grade3"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Grade3"
		"xpos"		"15"
		"ypos"		"112"
		"wide"		"110"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"1"
	}
	"Grade3Label"
	{
		"ControlName"		"Label"
		"fieldName"		"Grade3Label"
		"xpos"		"22"
		"ypos"		"112"
		"wide"		"96"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_POKER_EVT_Grade3"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Nick3"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Nick3"
		"xpos"		"128"
		"ypos"		"112"
		"wide"		"144"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"1"
	}
	"Nick3Label"
	{
		"ControlName"		"Label"
		"fieldName"		"Nick3Label"
		"xpos"		"135"
		"ypos"		"112"
		"wide"		"130"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Score3"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Score3"
		"xpos"		"276"
		"ypos"		"112"
		"wide"		"284"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"1"
	}
	"Score3Label"
	{
		"ControlName"		"Label"
		"fieldName"		"Score3Label"
		"xpos"		"283"
		"ypos"		"112"
		"wide"		"270"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Grade4"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Grade4"
		"xpos"		"15"
		"ypos"		"147"
		"wide"		"110"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"1"
	}
	"Grade4Label"
	{
		"ControlName"		"Label"
		"fieldName"		"Grade4Label"
		"xpos"		"22"
		"ypos"		"147"
		"wide"		"96"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_POKER_EVT_Grade4"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Nick4"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Nick4"
		"xpos"		"128"
		"ypos"		"147"
		"wide"		"144"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"1"
	}
	"Nick4Label"
	{
		"ControlName"		"Label"
		"fieldName"		"Nick4Label"
		"xpos"		"135"
		"ypos"		"147"
		"wide"		"130"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Score4"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Score4"
		"xpos"		"276"
		"ypos"		"147"
		"wide"		"284"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"1"
	}
	"Score4Label"
	{
		"ControlName"		"Label"
		"fieldName"		"Score4Label"
		"xpos"		"283"
		"ypos"		"147"
		"wide"		"270"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Grade5"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Grade5"
		"xpos"		"15"
		"ypos"		"182"
		"wide"		"110"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"1"
	}
	"Grade5Label"
	{
		"ControlName"		"Label"
		"fieldName"		"Grade5Label"
		"xpos"		"22"
		"ypos"		"182"
		"wide"		"96"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_POKER_EVT_Grade5"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Nick5"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Nick5"
		"xpos"		"128"
		"ypos"		"182"
		"wide"		"144"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"1"
	}
	"Nick5Label"
	{
		"ControlName"		"Label"
		"fieldName"		"Nick5Label"
		"xpos"		"135"
		"ypos"		"182"
		"wide"		"130"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Score5"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Score5"
		"xpos"		"276"
		"ypos"		"182"
		"wide"		"284"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"1"
	}
	"Score5Label"
	{
		"ControlName"		"Label"
		"fieldName"		"Score5Label"
		"xpos"		"283"
		"ypos"		"182"
		"wide"		"270"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Grade6"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Grade6"
		"xpos"		"15"
		"ypos"		"217"
		"wide"		"110"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"1"
	}
	"Grade6Label"
	{
		"ControlName"		"Label"
		"fieldName"		"Grade6Label"
		"xpos"		"22"
		"ypos"		"217"
		"wide"		"96"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_POKER_EVT_Grade6"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Nick6"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Nick6"
		"xpos"		"128"
		"ypos"		"217"
		"wide"		"144"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"1"
	}
	"Nick6Label"
	{
		"ControlName"		"Label"
		"fieldName"		"Nick6Label"
		"xpos"		"135"
		"ypos"		"217"
		"wide"		"130"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Score6"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Score6"
		"xpos"		"276"
		"ypos"		"217"
		"wide"		"284"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"Score6Label"
	{
		"ControlName"		"Label"
		"fieldName"		"Score6Label"
		"xpos"		"283"
		"ypos"		"217"
		"wide"		"270"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}																						
	"MyInfoMsg"
	{
		"ControlName"		"Label"
		"fieldName"		"MyInfoMsg"
		"xpos"		"15"
		"ypos"		"254"
		"wide"		"545"
		"tall"		"37"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"btn_ok"
	{
		"ControlName"		"Button"
		"fieldName"		"btn_ok"
		"xpos"		"184"
		"ypos"		"297"
		"wide"		"207"
		"tall"		"41"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Reward1_Btn"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	
}