"Popup_MapSelect_List1.res"
{
	"MapListDlg"
	{
		"ControlName"		"CMapListDlg"
		"fieldName"		"MapListDlg"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"638"
		"tall"		""
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"settitlebarvisible"		"1"
		"title"		"Untitle"
	}
	"MapBg1"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"MapBg1"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"200"
		"tall"		"134"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Map1"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Map1"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"200"
		"tall"		"97"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"HotIcon1"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HotIcon1"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"59"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"ExclusiveIcon1"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"ExclusiveIcon1"
		"xpos"		"2"
		"ypos"		"69"
		"wide"		"128"
		"tall"		"26"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"MapLabel1"
	{
		"ControlName"		"Label"
		"fieldName"		"MapLabel1"
		"xpos"		"10"
		"ypos"		"105"
		"wide"		"162"
		"tall"		"21"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"CheckButton1"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckButton1"
		"xpos"		"175"
		"ypos"		"106"
		"wide"		"19"
		"tall"		"19"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"MapBg2"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"MapBg2"
		"xpos"		"210"
		"ypos"		"0"
		"wide"		"200"
		"tall"		"134"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Map2"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Map2"
		"xpos"		"210"
		"ypos"		"0"
		"wide"		"200"
		"tall"		"97"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"HotIcon2"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HotIcon2"
		"xpos"		"210"
		"ypos"		"0"
		"wide"		"59"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"ExclusiveIcon2"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"ExclusiveIcon2"
		"xpos"		"212"
		"ypos"		"69"
		"wide"		"128"
		"tall"		"26"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"MapLabel2"
	{
		"ControlName"		"Label"
		"fieldName"		"MapLabel2"
		"xpos"		"220"
		"ypos"		"105"
		"wide"		"162"
		"tall"		"21"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"CheckButton2"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckButton2"
		"xpos"		"385"
		"ypos"		"106"
		"wide"		"19"
		"tall"		"19"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"MapBg3"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"MapBg3"
		"xpos"		"420"
		"ypos"		"0"
		"wide"		"200"
		"tall"		"134"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Map3"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Map3"
		"xpos"		"420"
		"ypos"		"0"
		"wide"		"200"
		"tall"		"97"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"HotIcon3"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HotIcon3"
		"xpos"		"420"
		"ypos"		"0"
		"wide"		"59"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"ExclusiveIcon3"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"ExclusiveIcon3"
		"xpos"		"422"
		"ypos"		"69"
		"wide"		"128"
		"tall"		"26"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"MapLabel3"
	{
		"ControlName"		"Label"
		"fieldName"		"MapLabel3"
		"xpos"		"430"
		"ypos"		"105"
		"wide"		"162"
		"tall"		"21"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"CheckButton3"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckButton3"
		"xpos"		"595"
		"ypos"		"106"
		"wide"		"19"
		"tall"		"19"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"MapBg4"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"MapBg4"
		"xpos"		"0"
		"ypos"		"147"
		"wide"		"200"
		"tall"		"134"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Map4"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Map4"
		"xpos"		"0"
		"ypos"		"147"
		"wide"		"200"
		"tall"		"97"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"HotIcon4"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HotIcon4"
		"xpos"		"0"
		"ypos"		"147"
		"wide"		"59"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"ExclusiveIcon4"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"ExclusiveIcon4"
		"xpos"		"2"
		"ypos"		"216"
		"wide"		"128"
		"tall"		"26"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"MapLabel4"
	{
		"ControlName"		"Label"
		"fieldName"		"MapLabel4"
		"xpos"		"10"
		"ypos"		"252"
		"wide"		"162"
		"tall"		"21"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"CheckButton4"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckButton4"
		"xpos"		"175"
		"ypos"		"253"
		"wide"		"19"
		"tall"		"19"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"MapBg5"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"MapBg5"
		"xpos"		"210"
		"ypos"		"147"
		"wide"		"200"
		"tall"		"134"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Map5"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Map5"
		"xpos"		"210"
		"ypos"		"147"
		"wide"		"200"
		"tall"		"97"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"HotIcon5"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HotIcon5"
		"xpos"		"210"
		"ypos"		"147"
		"wide"		"59"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"ExclusiveIcon5"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"ExclusiveIcon5"
		"xpos"		"212"
		"ypos"		"216"
		"wide"		"128"
		"tall"		"26"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"MapLabel5"
	{
		"ControlName"		"Label"
		"fieldName"		"MapLabel5"
		"xpos"		"220"
		"ypos"		"252"
		"wide"		"162"
		"tall"		"21"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"CheckButton5"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckButton5"
		"xpos"		"385"
		"ypos"		"253"
		"wide"		"19"
		"tall"		"19"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"MapBg6"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"MapBg6"
		"xpos"		"420"
		"ypos"		"147"
		"wide"		"200"
		"tall"		"134"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"Map6"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Map6"
		"xpos"		"420"
		"ypos"		"147"
		"wide"		"200"
		"tall"		"97"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"HotIcon6"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HotIcon6"
		"xpos"		"420"
		"ypos"		"147"
		"wide"		"59"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"ExclusiveIcon6"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"ExclusiveIcon6"
		"xpos"		"422"
		"ypos"		"216"
		"wide"		"128"
		"tall"		"26"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"MapLabel6"
	{
		"ControlName"		"Label"
		"fieldName"		"MapLabel6"
		"xpos"		"430"
		"ypos"		"252"
		"wide"		"162"
		"tall"		"21"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"CheckButton6"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckButton6"
		"xpos"		"595"
		"ypos"		"253"
		"wide"		"19"
		"tall"		"19"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"MapBg7"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"MapBg7"
		"xpos"		"0"
		"ypos"		"294"
		"wide"		"200"
		"tall"		"37"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"MapLabel7"
	{
		"ControlName"		"Label"
		"fieldName"		"MapLabel7"
		"xpos"		"10"
		"ypos"		"302"
		"wide"		"162"
		"tall"		"21"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"CheckButton7"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckButton7"
		"xpos"		"175"
		"ypos"		"303"
		"wide"		"19"
		"tall"		"19"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"MapBg8"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"MapBg8"
		"xpos"		"210"
		"ypos"		"294"
		"wide"		"200"
		"tall"		"37"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"MapLabel8"
	{
		"ControlName"		"Label"
		"fieldName"		"MapLabel8"
		"xpos"		"220"
		"ypos"		"302"
		"wide"		"162"
		"tall"		"21"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"CheckButton8"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckButton8"
		"xpos"		"385"
		"ypos"		"303"
		"wide"		"19"
		"tall"		"19"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"MapBg9"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"MapBg9"
		"xpos"		"420"
		"ypos"		"294"
		"wide"		"200"
		"tall"		"37"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"0"
	}
	"MapLabel9"
	{
		"ControlName"		"Label"
		"fieldName"		"MapLabel9"
		"xpos"		"430"
		"ypos"		"302"
		"wide"		"162"
		"tall"		"21"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Age"
		"wrap"		"0"
	}
	"CheckButton9"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"CheckButton9"
		"xpos"		"595"
		"ypos"		"303"
		"wide"		"19"
		"tall"		"19"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
}
 