"StatisticZombieTypeVerticalGraphDlg.res"
{
	"GraphBG"
	{
		"ControlName"		"NinePicsPanel"
		"fieldName"		"GraphBG"
		"xpos"		"59"
		"ypos"		"47"
		"wide"		"314"
		"tall"		"116"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"0"
		"scaleImage"		"1"
	}
	"GraphTitle"
	{
		"ControlName"		"Label"
		"fieldName"		"GraphTitle"
		"xpos"		"17"
		"ypos"		"13"
		"wide"		"365"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Statistic_AccumKillType"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default16"
		"wrap"		"0"
	}
	"YAxisElement1"
	{
		"ControlName"		"Label"
		"fieldName"		"YAxisElement1"
		"xpos"		"12"
		"ypos"		"154"
		"wide"		"44"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"0"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default"
		"wrap"		"0"
	}
	"YAxisElement2"
	{
		"ControlName"		"Label"
		"fieldName"		"YAxisElement2"
		"xpos"		"12"
		"ypos"		"118"
		"wide"		"44"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"0"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default"
		"wrap"		"0"
	}
	"YAxisElement3"
	{
		"ControlName"		"Label"
		"fieldName"		"YAxisElement3"
		"xpos"		"12"
		"ypos"		"82"
		"wide"		"44"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"0"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default"
		"wrap"		"0"
	}
	"YAxisElement4"
	{
		"ControlName"		"Label"
		"fieldName"		"YAxisElement4"
		"xpos"		"12"
		"ypos"		"46"
		"wide"		"44"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"0"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default"
		"wrap"		"0"
	}
	"XAxisElement1"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"XAxisElement1"
		"xpos"		"74"
		"ypos"		"167"
		"wide"		"20"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/zb_normal"
	}
	"XAxisElement2"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"XAxisElement2"
		"xpos"		"98"
		"ypos"		"167"
		"wide"		"20"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/zb_SpeedZombie"
	}
	"XAxisElement3"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"XAxisElement3"
		"xpos"		"122"
		"ypos"		"167"
		"wide"		"20"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/zb_HeavyZombie"
	}
	"XAxisElement4"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"XAxisElement4"
		"xpos"		"146"
		"ypos"		"167"
		"wide"		"20"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/zb_PCZombie"
	}
	"XAxisElement5"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"XAxisElement5"
		"xpos"		"170"
		"ypos"		"167"
		"wide"		"20"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/zb_ZombiDoctor"
	}
	"XAxisElement6"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"XAxisElement6"
		"xpos"		"194"
		"ypos"		"167"
		"wide"		"20"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/zb_Deimos"
	}
	"XAxisElement7"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"XAxisElement7"
		"xpos"		"218"
		"ypos"		"167"
		"wide"		"20"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/zb_Deimos2"
	}
	"XAxisElement8"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"XAxisElement8"
		"xpos"		"242"
		"ypos"		"167"
		"wide"		"20"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/zb_undertaker"
	}
	"XAxisElement9"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"XAxisElement8"
		"xpos"		"266"
		"ypos"		"167"
		"wide"		"20"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/zb_Witch"
	}
	"XAxisElement10"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"XAxisElement10"
		"xpos"		"290"
		"ypos"		"167"
		"wide"		"20"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/zb_chinazombie"
	}
	"XAxisElement11"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"XAxisElement11"
		"xpos"		"314"
		"ypos"		"167"
		"wide"		"20"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/zb_boomer"
	}
	"XAxisElement12"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"XAxisElement12"
		"xpos"		"338"
		"ypos"		"167"
		"wide"		"20"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/zb_residentzombi"
	}
	"GraphElement1"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"GraphElement1"
		"xpos"		"79"
		"ypos"		"48"
		"wide"		"10"
		"tall"		"114"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/bar_gray"
	}
	"GraphElement2"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"GraphElement2"
		"xpos"		"103"
		"ypos"		"48"
		"wide"		"10"
		"tall"		"114"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/bar_gray"
	}
	"GraphElement3"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"GraphElement3"
		"xpos"		"127"
		"ypos"		"48"
		"wide"		"10"
		"tall"		"114"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/bar_gray"
	}
	"GraphElement4"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"GraphElement4"
		"xpos"		"151"
		"ypos"		"48"
		"wide"		"10"
		"tall"		"114"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/bar_gray"
	}
	"GraphElement5"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"GraphElement5"
		"xpos"		"175"
		"ypos"		"48"
		"wide"		"10"
		"tall"		"114"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/bar_gray"
	}
	"GraphElement6"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"GraphElement6"
		"xpos"		"199"
		"ypos"		"48"
		"wide"		"10"
		"tall"		"114"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/bar_gray"
	}
	"GraphElement7"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"GraphElement7"
		"xpos"		"223"
		"ypos"		"48"
		"wide"		"10"
		"tall"		"114"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/bar_gray"
	}
	"GraphElement8"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"GraphElement8"
		"xpos"		"247"
		"ypos"		"48"
		"wide"		"10"
		"tall"		"114"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/bar_gray"
	}
	"GraphElement9"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"GraphElement9"
		"xpos"		"271"
		"ypos"		"48"
		"wide"		"10"
		"tall"		"114"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/bar_gray"
	}
	"GraphElement10"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"GraphElement10"
		"xpos"		"295"
		"ypos"		"48"
		"wide"		"10"
		"tall"		"114"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/bar_gray"
	}
	"GraphElement11"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"GraphElement11"
		"xpos"		"319"
		"ypos"		"48"
		"wide"		"10"
		"tall"		"114"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/bar_gray"
	}
	"GraphElement12"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"GraphElement12"
		"xpos"		"343"
		"ypos"		"48"
		"wide"		"10"
		"tall"		"114"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/bar_gray"
	}
}
 
