"StatisticZombieTypeVerticalGraphDlg.res"
{
	"GraphBG"
	{
		"ControlName"		"NinePicsPanel"
		"fieldName"		"GraphBG"
		"xpos"		"59"
		"ypos"		"47"
		"wide"		"314"
		"tall"		"116"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"0"
		"scaleImage"		"1"
	}
	"GraphTitle"
	{
		"ControlName"		"Label"
		"fieldName"		"GraphTitle"
		"xpos"		"17"
		"ypos"		"13"
		"wide"		"365"
		"tall"		"20"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Statistic_AvgLiveTime10Round"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default16"
		"wrap"		"0"
	}
	"YAxisElement1"
	{
		"ControlName"		"Label"
		"fieldName"		"YAxisElement1"
		"xpos"		"12"
		"ypos"		"154"
		"wide"		"44"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"0"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default"
		"wrap"		"0"
	}
	"YAxisElement2"
	{
		"ControlName"		"Label"
		"fieldName"		"YAxisElement2"
		"xpos"		"12"
		"ypos"		"118"
		"wide"		"44"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"0"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default"
		"wrap"		"0"
	}
	"YAxisElement3"
	{
		"ControlName"		"Label"
		"fieldName"		"YAxisElement3"
		"xpos"		"12"
		"ypos"		"82"
		"wide"		"44"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"0"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default"
		"wrap"		"0"
	}
	"YAxisElement4"
	{
		"ControlName"		"Label"
		"fieldName"		"YAxisElement4"
		"xpos"		"12"
		"ypos"		"46"
		"wide"		"44"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"0"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default"
		"wrap"		"0"
	}
	"XAxisElement1"
	{
		"ControlName"		"Label"
		"fieldName"		"XAxisElement1"
		"xpos"		"78"
		"ypos"		"170"
		"wide"		"24"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Statistic_1R"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default"
		"wrap"		"0"
	}
	"XAxisElement2"
	{
		"ControlName"		"Label"
		"fieldName"		"XAxisElement2"
		"xpos"		"106"
		"ypos"		"170"
		"wide"		"24"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Statistic_2R"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default"
		"wrap"		"0"
	}
	"XAxisElement3"
	{
		"ControlName"		"Label"
		"fieldName"		"XAxisElement3"
		"xpos"		"134"
		"ypos"		"170"
		"wide"		"24"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Statistic_3R"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default"
		"wrap"		"0"
	}
	"XAxisElement4"
	{
		"ControlName"		"Label"
		"fieldName"		"XAxisElement4"
		"xpos"		"162"
		"ypos"		"170"
		"wide"		"24"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Statistic_4R"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default"
		"wrap"		"0"
	}
	"XAxisElement5"
	{
		"ControlName"		"Label"
		"fieldName"		"XAxisElement5"
		"xpos"		"190"
		"ypos"		"170"
		"wide"		"24"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Statistic_5R"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default"
		"wrap"		"0"
	}
	"XAxisElement6"
	{
		"ControlName"		"Label"
		"fieldName"		"XAxisElement6"
		"xpos"		"218"
		"ypos"		"170"
		"wide"		"24"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Statistic_6R"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default"
		"wrap"		"0"
	}
	"XAxisElement7"
	{
		"ControlName"		"Label"
		"fieldName"		"XAxisElement7"
		"xpos"		"246"
		"ypos"		"170"
		"wide"		"24"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Statistic_7R"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default"
		"wrap"		"0"
	}
	"XAxisElement8"
	{
		"ControlName"		"Label"
		"fieldName"		"XAxisElement8"
		"xpos"		"274"
		"ypos"		"170"
		"wide"		"24"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Statistic_8R"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default"
		"wrap"		"0"
	}
	"XAxisElement9"
	{
		"ControlName"		"Label"
		"fieldName"		"XAxisElement9"
		"xpos"		"302"
		"ypos"		"170"
		"wide"		"24"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Statistic_9R"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default"
		"wrap"		"0"
	}
	"XAxisElement10"
	{
		"ControlName"		"Label"
		"fieldName"		"XAxisElement10"
		"xpos"		"330"
		"ypos"		"170"
		"wide"		"24"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#CSO_Statistic_10R"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Default"
		"wrap"		"0"
	}
	"GraphElement1"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"GraphElement1"
		"xpos"		"85"
		"ypos"		"48"
		"wide"		"10"
		"tall"		"114"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/bar_gray"
	}
	"GraphElement2"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"GraphElement2"
		"xpos"		"113"
		"ypos"		"48"
		"wide"		"10"
		"tall"		"114"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/bar_gray"
	}
	"GraphElement3"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"GraphElement3"
		"xpos"		"141"
		"ypos"		"48"
		"wide"		"10"
		"tall"		"114"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/bar_gray"
	}
	"GraphElement4"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"GraphElement4"
		"xpos"		"169"
		"ypos"		"48"
		"wide"		"10"
		"tall"		"114"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/bar_gray"
	}
	"GraphElement5"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"GraphElement5"
		"xpos"		"197"
		"ypos"		"48"
		"wide"		"10"
		"tall"		"114"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/bar_gray"
	}
	"GraphElement6"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"GraphElement6"
		"xpos"		"225"
		"ypos"		"48"
		"wide"		"10"
		"tall"		"114"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/bar_gray"
	}
	"GraphElement7"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"GraphElement7"
		"xpos"		"253"
		"ypos"		"48"
		"wide"		"10"
		"tall"		"114"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/bar_gray"
	}
	"GraphElement8"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"GraphElement8"
		"xpos"		"281"
		"ypos"		"48"
		"wide"		"10"
		"tall"		"114"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/bar_gray"
	}
	"GraphElement9"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"GraphElement9"
		"xpos"		"309"
		"ypos"		"48"
		"wide"		"10"
		"tall"		"114"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/bar_gray"
	}
	"GraphElement10"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"GraphElement10"
		"xpos"		"337"
		"ypos"		"48"
		"wide"		"10"
		"tall"		"114"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"scaleImage"		"1"
		"image"			"resource/zmstate/bar_gray"
	}
}
 
